---
# This is the top-level playbook that defines our entire infrastructure.

- hosts: biroute
  user: deploy
  sudo: True
  gather_facts: True
  vars_files:
    - vars/common.yml
    - vars/defaults.yml
    - vars/user.yml


  roles:
    - common
    - { role : mysql, tags: ['mysql'] }
    - { role : mailserver, tags: ['mailserver'] }
    #- webmail
    #- blog
    #- ircbouncer
    #- xmpp
    #- owncloud
    #- vpn
    #- tarsnap
    #- news
    #- git
    #- newebe
    #- readlater
    #- monitoring  # Monitoring role should be last. See roles/monitoring/README.md
