- name: Install Postfix 9.1 and related packages
  apt: pkg={{ item }} state=installed
  with_items:
    - libsasl2-modules
    - postfix
    - postfix-pcre
    - postfix-mysql
    - postgrey
    - python-mysqldb
    - sasl2-bin

- name: Create database for mail server
  mysql_db: login_user={{ db_admin_username }} login_password="{{ db_admin_password }}" name={{ mail_db_database }} target=/etc/postfix/import.sql state=present
  register: test_createdb

- name: Create user for mail server
  mysql_user: login_user={{ db_admin_username }} login_password="{{ db_admin_password }}" name={{ mail_db_database }} password={{ mail_db_password }} priv={{ mail_db_database }}.*:ALL state=present

- name: Copy import.sql
  template: src=mailserver.sql.j2 dest=/etc/postfix/import.sql owner=root group=root mode=0600

- name: Import base schema
  mysql_db: login_user={{ mail_db_username }} login_password="{{ mail_db_password }}" name={{ mail_db_database }} state=import target=/etc/postfix/import.sql
  when: test_createdb.changed

- name: Create postfix maps directory
  file: path=/etc/postfix/maps state=directory owner=root group=root
  when: mail_header_privacy == 1

- name: Copy smtp_header_checks.pcre
  copy: src=etc_postfix_maps_smtp_header_checks.pcre dest=/etc/postfix/maps/smtp_header_checks.pcre owner=root group=root
  when: mail_header_privacy == 1

- name: Copy main.cf
  template: src=etc_postfix_main.cf.j2 dest=/etc/postfix/main.cf owner=root group=root
  notify: restart postfix

- name: Copy master.cf
  copy: src=etc_postfix_master.cf dest=/etc/postfix/master.cf owner=root group=root
  notify: restart postfix

- name: Copy additional postfix configuration files
  template: src=etc_postfix_{{ item }}.j2 dest=/etc/postfix/{{ item }} owner=root group=root
  with_items:
    - mysql-virtual-alias-maps.cf
    - mysql-virtual-mailbox-domains.cf
    - mysql-virtual-mailbox-maps.cf
  notify: restart postfix

- name: Set firewall rules for postfix
  ufw: rule=allow port={{ item }} proto=tcp
  with_items:
    - smtp
    - ssmtp
