---
  - name: install mysql-server
    action: apt name=mysql-server
    register: test_install

  - name: mysql_secure_installation
    action: template src=mysql_secure_installation.j2 dest=/tmp/mysql_secure_installation owner=root group=root mode=0600
    when: test_install.changed

  - name: launch mysql_secure_installation
    action: shell cat /tmp/mysql_secure_installation | mysql_secure_installation
    when: test_install.changed

  - name: delete mysql_secure_installation
    action: file dest=/tmp/mysql_secure_installation state=absent
    when: test_install.changed

  - name: write conf.d/mysqld.cnf
    action: template src=mysqld.cnf.j2 dest=/etc/mysql/conf.d/mysqld.cnf
    notify: restart mysql

  - name: write conf.d/client.cnf
    action: template src=client.cnf.j2 dest=/etc/mysql/conf.d/client.cnf
    notify: restart mysql

  - name: restart mysql
    action: service name=mysql state=restarted enabled=yes
    when: test_install.changed

  - include: phpmyadmin.yml tags=phpmyadmin
