---
# Defines tasks applicable across all machines in the infrastructure.


- name: Set up closest mirror
  template: src=apt_sources.list.j2 dest=/etc/apt/sources.list

- name: Update apt cache
  apt: update_cache=yes

- name: Upgrade all safe packages
  apt: upgrade=safe

- name: Install necessities and nice-to-haves
  apt: pkg={{ item }} state=installed
  with_items:
#    - apache2
    - apt-transport-https
    - apticron
    #- build-essential
    - debian-goodies
    - dos2unix
    - git
    - htop
    - iftop
    - iotop
    - jed
    - mosh
    - multitail
    - python-software-properties
    - ruby
    - screen
    - sudo
    - tree
    #- update-notifier-common
    - vim
    - weechat

- name: Set timezone to UTC
  action: shell echo Europe/Paris > /etc/timezone

- name: Set localtime to UTC
  file: src='/usr/share/zoneinfo/Etc/GMT+1' dest=/etc/localtime

- name: Reconfigure tzdata
  action: command dpkg-reconfigure -f noninteractive tzdata

- name: Install unattended upgrades (Debian/Ubuntu only)
  apt: pkg=unattended-upgrades state=installed

- name: Apticron email configuration
  template: src=apticron.conf.j2 dest=/etc/apticron/apticron.conf

# - name: Disable default Apache site
#   command: a2dissite 000-default removes=/etc/apache2/sites-enabled/000-default
#   notify: restart apache

#- name: Enable Apache headers module
#  command: a2enmod headers creates=/etc/apache2/mods-enabled/headers.load
#  notify: restart apache

#- name: Set ServerName for Apache
#  template: src=fqdn.j2 dest=/etc/apache2/conf-available/fqdn.conf

#- name: Enable override configurations
#  command: a2enconf fqdn
#  notify: restart apache

- include: users.yml tags=users
#- include: ssl.yml tags=ssl
- include: ufw.yml tags=ufw
- include: security.yml tags=security
- include: ntp.yml tags=ntp


  #- include: google_auth.yml tags=google_auth
#  when: ansible_distribution_release != 'trusty'
#- include: google_auth_mod.yml tags=google_auth
#  when: ansible_distribution_release == 'trusty'
